[package]
name = "validation_v3"
version = "0.1.0"
description = "SATP Validation V3 — verification level computation via CPI to Identity V3"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "=1.0.0"
