#!/usr/bin/env node
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const root = resolve(new URL('..', import.meta.url).pathname);
const canonicalOutDir = resolve(root, 'idls/v3');
const clientDiscriminatorPath = resolve(root, 'packages/satp-client/src/v3-idl-discriminators.js');
const sourceRef = 'brainAI-bot/satp working tree';
const generationCommand = 'node scripts/generate-v3-idls.mjs';
const checkOnly = process.argv.includes('--check');

const programs = [
  {
    name: 'identity_v3',
    address: '7qmfg4CgiXVDZGBeUkSkMsacKjCRty2xEAugPK4nfvZQ',
    deployments: {
      devnet: '7qmfg4CgiXVDZGBeUkSkMsacKjCRty2xEAugPK4nfvZQ',
      localnet: '7qmfg4CgiXVDZGBeUkSkMsacKjCRty2xEAugPK4nfvZQ',
      mainnet: 'GTppU4E44BqXTQgbqMZ68ozFzhP1TLty3EGnzzjtNZfG',
    },
  },
  {
    name: 'reviews_v3',
    address: '3yVFrWCpBnQdWNqmiCG9EpoZq7WYeQ421Gx5sUh41Kwk',
    deployments: {
      devnet: '3yVFrWCpBnQdWNqmiCG9EpoZq7WYeQ421Gx5sUh41Kwk',
      localnet: '3yVFrWCpBnQdWNqmiCG9EpoZq7WYeQ421Gx5sUh41Kwk',
      mainnet: 'r9XX4frcqxxAZ6Au9V5PA3EAxs1zoNckqLLmoSRcNr4',
    },
  },
  {
    name: 'attestations_v3',
    address: '55aS2y5Lhe427iW4cgo2nmZPrxwH3F7BWkw6MnoEm4zw',
    deployments: {
      devnet: '55aS2y5Lhe427iW4cgo2nmZPrxwH3F7BWkw6MnoEm4zw',
      localnet: '55aS2y5Lhe427iW4cgo2nmZPrxwH3F7BWkw6MnoEm4zw',
      mainnet: '6Xd1dAQJPvQRJ4Ntr6LtPTjDjPUZ8nfnmYLZaZ2DtrdD',
    },
  },
  {
    name: 'reputation_v3',
    address: 'CtmZ1fHaypt3R6wbeiGawiRnjzRK9T8jsECk9mET9AK9',
    deployments: {
      devnet: 'CtmZ1fHaypt3R6wbeiGawiRnjzRK9T8jsECk9mET9AK9',
      localnet: 'CtmZ1fHaypt3R6wbeiGawiRnjzRK9T8jsECk9mET9AK9',
      mainnet: '2Lz7KzMvKdrGeAuS8WPHu7jK2yScrnKVgacpYVEuDjkJ',
    },
  },
  {
    name: 'validation_v3',
    address: 'DLB76DzAFY8KNuvnP79BZW3cehGreEQTeGDvFCNd2Ekj',
    deployments: {
      devnet: 'DLB76DzAFY8KNuvnP79BZW3cehGreEQTeGDvFCNd2Ekj',
      localnet: 'DLB76DzAFY8KNuvnP79BZW3cehGreEQTeGDvFCNd2Ekj',
      mainnet: '6rYRiCYidJYV7QvKrzKGgNu4oMh6BAvynked69R7xMbV',
    },
  },
  {
    name: 'escrow_v3',
    address: 'HXCUWKR2NvRcZ7rNAJHwPcH6QAAWaLR4bRFbfyuDND6C',
    deployments: {
      devnet: 'B1Se8SPx7GLUisa4LYeXY1tDZy5TviJrsV2yMLgqUXmg',
      localnet: 'B1Se8SPx7GLUisa4LYeXY1tDZy5TviJrsV2yMLgqUXmg',
      mainnet: 'HXCUWKR2NvRcZ7rNAJHwPcH6QAAWaLR4bRFbfyuDND6C',
    },
  },
];

function sha256(value) {
  return createHash('sha256').update(value).digest('hex');
}

function stable(value) {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.keys(value).sort().map((key) => [key, stable(value[key])]));
  }
  return value;
}

function pretty(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function bareAccountName(name) {
  return name.includes('::') ? name.split('::').pop() : name;
}

function clientDiscriminatorModule(idls) {
  const entries = [];
  for (const { idl } of idls) {
    for (const account of idl.accounts || []) {
      if (!Array.isArray(account.discriminator) || account.discriminator.length !== 8) {
        throw new Error(`${idl.metadata?.name || 'unknown IDL'}: account ${account.name} is missing an 8-byte discriminator`);
      }
      entries.push([bareAccountName(account.name), account.discriminator]);
    }
  }
  entries.sort(([left], [right]) => left.localeCompare(right));

  const lines = [
    "'use strict';",
    '',
    '// Generated by `node scripts/generate-v3-idls.mjs`; do not edit by hand.',
    'const V3_IDL_ACCOUNT_DISCRIMINATORS = Object.freeze({',
  ];
  for (const [name, discriminator] of entries) {
    lines.push(`  ${JSON.stringify(name)}: Object.freeze([${discriminator.join(', ')}]),`);
  }
  lines.push('});', '', 'module.exports = {', '  V3_IDL_ACCOUNT_DISCRIMINATORS,', '};', '');
  return lines.join('\n');
}

function extractIdl(output, program) {
  const marker = /--- IDL begin program ---\s*([\s\S]*?)\s*--- IDL end program ---/m;
  const match = output.match(marker);
  if (!match) {
    throw new Error(`${program}: generated IDL markers not found in cargo test output`);
  }
  return JSON.parse(match[1]);
}

function generate(program) {
  const features = program.name === 'escrow_v3' ? 'idl-build,mainnet' : 'idl-build';
  const output = execFileSync('cargo', [
    '+1.89.0',
    'test',
    '-p',
    program.name,
    '--features',
    features,
    '__anchor_private_print_idl',
    '--',
    '--show-output',
  ], {
    cwd: root,
    encoding: 'utf8',
    env: { ...process.env, CARGO_TERM_COLOR: 'never' },
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  const idl = extractIdl(output, program.name);
  if (idl.metadata?.name !== program.name) {
    throw new Error(`${program.name}: metadata.name mismatch: ${idl.metadata?.name}`);
  }
  idl.address = program.address;
  idl.metadata = {
    ...idl.metadata,
    deployments: program.deployments,
  };
  return idl;
}

if (!checkOnly) {
  mkdirSync(canonicalOutDir, { recursive: true });
}

const generated = [];
const generatedIdls = [];
for (const program of programs) {
  const idl = generate(program);
  const body = pretty(idl);
  const outPath = join(canonicalOutDir, `${program.name}.json`);
  generatedIdls.push({ program: program.name, idl });
  if (checkOnly) {
    if (!existsSync(outPath)) {
      throw new Error(`missing generated IDL ${relative(root, outPath)}`);
    }
    const committed = readFileSync(outPath, 'utf8');
    if (committed !== body) {
      throw new Error(`${relative(root, outPath)} does not match generated source IDL`);
    }
  } else {
    writeFileSync(outPath, body);
  }
  generated.push({
    program: program.name,
    address: idl.address,
    deployments: idl.metadata.deployments,
    idl: relative(root, outPath),
    sha256: sha256(body),
    stable_sha256: sha256(pretty(stable(idl))),
    instructions: idl.instructions?.length ?? 0,
    accounts: idl.accounts?.length ?? 0,
    types: idl.types?.length ?? 0,
    errors: idl.errors?.length ?? 0,
  });
}

const clientDiscriminatorBody = clientDiscriminatorModule(generatedIdls);
if (checkOnly) {
  if (!existsSync(clientDiscriminatorPath)) {
    throw new Error(`missing generated client discriminator metadata ${relative(root, clientDiscriminatorPath)}`);
  }
  const committed = readFileSync(clientDiscriminatorPath, 'utf8');
  if (committed !== clientDiscriminatorBody) {
    throw new Error(`${relative(root, clientDiscriminatorPath)} does not match generated V3 IDL discriminator metadata`);
  }
} else {
  writeFileSync(clientDiscriminatorPath, clientDiscriminatorBody);
}

const result = {
  ok: true,
  mode: checkOnly ? 'check' : 'write',
  source: sourceRef,
  command: generationCommand,
  client_discriminator_metadata: relative(root, clientDiscriminatorPath),
  programs: generated,
};

console.log(JSON.stringify(result, null, 2));
